// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using  QuizGame.Models;
//
//    var booster = Booster.FromJson(jsonString);

namespace MagicQuizDesktop.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using MagicQuizDesktop.Services;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Booster
    {
        public string BoosterName { get; set; }
        public bool Usable { get; set; }
        public IBoosterAction BoosterAction { get; set; }

    }
}
