// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using  QuizGame.Models;
//
//    var userBooster = UserBooster.FromJson(jsonString);

namespace MagicQuizDesktop.Models
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class UserBooster
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("user_id")]
        public long Userid { get; set; }

        [JsonProperty("booster_id")]
        public long Boosterid { get; set; }

        [JsonProperty("used")]
        public bool Used { get; set; }

        [JsonProperty("created_at")]
        public DateTimeOffset CreatedAt { get; set; }

        [JsonProperty("updated_at")]
        public DateTimeOffset UpdatedAt { get; set; }

        [JsonProperty("booster")]
        public Booster Booster { get; set; }
    }


    public partial class UserBooster
    {
        public static UserBooster[] FromJson(string json) => JsonConvert.DeserializeObject<UserBooster[]>(json, MagicQuizDesktop.Models.Converter.Settings);
    }

}
